### ISSUE TITLE
PyPi version fails to install on Mac due to  '#include <malloc.h>' in jly_3ddt.hpp file

### ISSUE THREAD

**Issue by connorhazen** [aalavandhaann/go-icp_cython#3]

**Comment by aalavandhaann** [comment]
Did you try compiling yourself with`python setup.py build`? Here is a link similar to the issue you are facing on malloc.h https://stackoverflow.com/questions/56463049/should-mac-osx-have-a-malloc-h-file

Try and let me know if you still have difficulties.

Regards,
#0K

**Comment by connorhazen** [comment]
Short follow up: I am trying to simplify the install process as I am packaging a script for inexperienced user. I learned they are using windows which I had hoped would simplify things. However a new issue arose again when using pip on windows. 

 UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3658: character maps to <undefined>
    FOUND AUTOWRAP LIBRARY, PROCEED
    PRECOMPILE USING AUTOWRAP BEFORE PROCEEDING
    Autowrap has wrapped 4 classes, 13 methods and 0 enums
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Any advice?

running Windows 10 - python 3.8.5

**Comment by aalavandhaann** [comment]
I believe it is coming from the description text. Just make it into a empty
string and try compiling

**Comment by connorhazen** [comment]
No luck. Getting this error "error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2". Any advice. Should I use a different compiler than visual studio, mingw etc

**Comment by connorhazen** [comment]
When manually compiling without visual studio "error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/"

**Comment by aalavandhaann** [comment]
Hi,

Did you try installing through pip? Was [README.md](https://github.com/aalavandhaann/go-icp_cython/blob/master/README.md) not useful? Did it not work correctly? Can you share more information to debug this problem? 

Looks like you don't have C++ 14.0. Install the compiler and the package should compile for you

Regards,
#0K

**Comment by connorhazen** [comment]
Tried pip installation. Error is still thrown. Currently running on 3.8.2 windows 10 with visual studio build tools and c++ compiler for 14.27.

**Comment by aalavandhaann** [comment]
I cannot magically solve this problem unless you share the complete error
logs. I can only keep guessing

**Comment by connorhazen** [comment]
** Pip Install on conda VM:** 

pip install py-goicp --user
Collecting py-goicp
  Using cached py_goicp-0.0.4.tar.gz (40 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\19707\miniconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\19707\\AppData\\Local\\Temp\\pip-install-7d74ami2\\py-goicp\\setup.py'"'"'; __file__='"'"'C:\\Users\\19707\\AppData\\Local\\Temp\\pip-install-7d74ami2\\py-goicp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\19707\AppData\Local\Temp\pip-install-7d74ami2\py-goicp\pip-egg-info'
         cwd: C:\Users\19707\AppData\Local\Temp\pip-install-7d74ami2\py-goicp\
    Complete output (73 lines):
    Level 25:root:parsing progress 0 out of 1
    INFO:root:start resolving decls
    INFO:root:resolve_inheritance for POINT3D
    INFO:root:resolve_inheritance for ROTNODE
    INFO:root:resolve_inheritance for TRANSNODE
    INFO:root:resolve_inheritance for GoICP
    INFO:root:resolve class decl POINT3D
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void POINT3D ([])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void POINT3D (['float ', 'float ', 'float '])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void pointToString ([])'
    INFO:root:resolve class decl ROTNODE
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void ROTNODE ([])'
    INFO:root:resolve class decl TRANSNODE
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void TRANSNODE ([])'
    INFO:root:resolve class decl GoICP
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void GoICP ([])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: float Register ([])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void BuildDT ([])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: libcpp_vector[libcpp_vector[double]] optimalRotation ([])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: libcpp_vector[double] optimalTranslation ([])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void loadModelAndData (['int ', 'libcpp_vector[POINT3D] ', 'int ', 'libcpp_vector[POINT3D] '])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void setInitNodeRot (['ROTNODE & '])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void setInitNodeTrans (['TRANSNODE & '])'
    INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void setDTSizeAndFactor (['int ', 'double '])'
    INFO:root:register <autowrap.ConversionProvider.IntegerConverter object at 0x000002261C272F40>
    INFO:root:register <autowrap.ConversionProvider.FloatConverter object at 0x000002261CD37A00>
    INFO:root:register <autowrap.ConversionProvider.DoubleConverter object at 0x000002261CD379A0>
    INFO:root:register <autowrap.ConversionProvider.ConstCharPtrConverter object at 0x000002261CD80160>
    INFO:root:register <autowrap.ConversionProvider.CharPtrConverter object at 0x000002261CD807F0>
    INFO:root:register <autowrap.ConversionProvider.CharConverter object at 0x000002261CD80FA0>
    INFO:root:register <autowrap.ConversionProvider.StdStringConverter object at 0x000002261CD902B0>
    INFO:root:register <autowrap.ConversionProvider.StdStringUnicodeConverter object at 0x000002261CD90880>
    INFO:root:register <autowrap.ConversionProvider.StdStringUnicodeOutputConverter object at 0x000002261CD908E0>
    INFO:root:register <autowrap.ConversionProvider.StdVectorConverter object at 0x000002261CD90940>
    INFO:root:register <autowrap.ConversionProvider.StdSetConverter object at 0x000002261CD909A0>
    INFO:root:register <autowrap.ConversionProvider.StdMapConverter object at 0x000002261CD90A00>
    INFO:root:register <autowrap.ConversionProvider.StdPairConverter object at 0x000002261CD90A60>
    INFO:root:register <autowrap.ConversionProvider.VoidConverter object at 0x000002261CD90AC0>
    INFO:root:register <autowrap.ConversionProvider.SharedPtrConverter object at 0x000002261CD90B20>
    INFO:root:register <autowrap.ConversionProvider.TypeToWrapConverter object at 0x000002261CD90BB0>
    INFO:root:register <autowrap.ConversionProvider.TypeToWrapConverter object at 0x000002261CD90C10>
    INFO:root:register <autowrap.ConversionProvider.TypeToWrapConverter object at 0x000002261CD90C70>
    INFO:root:register <autowrap.ConversionProvider.TypeToWrapConverter object at 0x000002261CD90CD0>
    INFO:root:Create foreign imports for module C:\Users\19707\AppData\Local\Temp\pip-install-7d74ami2\py-goicp\src\py_goicp.pyx
    INFO:root:create wrapper for class GoICP
    INFO:root:   create wrapper for non overloaded constructor __init__
    INFO:root:   create wrapper for Register ('float Register()')
    INFO:root:   create wrapper for BuildDT ('void BuildDT()')
    INFO:root:   create wrapper for optimalRotation ('libcpp_vector[libcpp_vector[double]] optimalRotation()')
    INFO:root:   create wrapper for optimalTranslation ('libcpp_vector[double] optimalTranslation()')
    INFO:root:   create wrapper for loadModelAndData ('void loadModelAndData(int, libcpp_vector[POINT3D], int, libcpp_vector[POINT3D])')
    INFO:root:   create wrapper for setInitNodeRot ('void setInitNodeRot(ROTNODE &)')
    INFO:root:   create wrapper for setInitNodeTrans ('void setInitNodeTrans(TRANSNODE &)')
    INFO:root:   create wrapper for setDTSizeAndFactor ('void setDTSizeAndFactor(int, double)')
    INFO:root:create wrapper for class POINT3D
    INFO:root:   create wrapper for non overloaded constructor _init_0
    INFO:root:   create wrapper for non overloaded constructor _init_1
    INFO:root:   create wrapper decl for overloaded method __init__
    INFO:root:   create wrapper for pointToString ('void pointToString()')
    INFO:root:create wrapper for class ROTNODE
    INFO:root:   create wrapper for non overloaded constructor __init__
    INFO:root:create wrapper for class TRANSNODE
    INFO:root:   create wrapper for non overloaded constructor __init__
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\19707\AppData\Local\Temp\pip-install-7d74ami2\py-goicp\setup.py", line 66, in <module>
        long_description=open('README.md').read(),
      File "C:\Users\19707\miniconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3658: character maps to <undefined>
    FOUND AUTOWRAP LIBRARY, PROCEED
    PRECOMPILE USING AUTOWRAP BEFORE PROCEEDING
    Autowrap has wrapped 4 classes, 13 methods and 0 enums
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.




**Manual Compile:**

python setup.py build_ext --inplace
FOUND AUTOWRAP LIBRARY, PROCEED
PRECOMPILE USING AUTOWRAP BEFORE PROCEEDING
Level 25:root:parsing progress 0 out of 1
INFO:root:start resolving decls
INFO:root:resolve_inheritance for POINT3D
INFO:root:resolve_inheritance for ROTNODE
INFO:root:resolve_inheritance for TRANSNODE
INFO:root:resolve_inheritance for GoICP
INFO:root:resolve class decl POINT3D
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void POINT3D ([])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void POINT3D (['float ', 'float ', 'float '])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void pointToString ([])'
INFO:root:resolve class decl ROTNODE
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void ROTNODE ([])'
INFO:root:resolve class decl TRANSNODE
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void TRANSNODE ([])'
INFO:root:resolve class decl GoICP
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void GoICP ([])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: float Register ([])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void BuildDT ([])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: libcpp_vector[libcpp_vector[double]] optimalRotation ([])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: libcpp_vector[double] optimalTranslation ([])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void loadModelAndData (['int ', 'libcpp_vector[POINT3D] ', 'int ', 'libcpp_vector[POINT3D] '])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void setInitNodeRot (['ROTNODE & '])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void setInitNodeTrans (['TRANSNODE & '])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void setDTSizeAndFactor (['int ', 'double '])'
INFO:root:register <autowrap.ConversionProvider.IntegerConverter object at 0x00000164DE7FEFD0>
INFO:root:register <autowrap.ConversionProvider.FloatConverter object at 0x00000164DDE122B0>
INFO:root:register <autowrap.ConversionProvider.DoubleConverter object at 0x00000164DE813040>
INFO:root:register <autowrap.ConversionProvider.ConstCharPtrConverter object at 0x00000164DE99B760>
INFO:root:register <autowrap.ConversionProvider.CharPtrConverter object at 0x00000164DE99BDF0>
INFO:root:register <autowrap.ConversionProvider.CharConverter object at 0x00000164DE9AA640>
INFO:root:register <autowrap.ConversionProvider.StdStringConverter object at 0x00000164DE9AA910>
INFO:root:register <autowrap.ConversionProvider.StdStringUnicodeConverter object at 0x00000164DE9AAEE0>
INFO:root:register <autowrap.ConversionProvider.StdStringUnicodeOutputConverter object at 0x00000164DE9AAF40>
INFO:root:register <autowrap.ConversionProvider.StdVectorConverter object at 0x00000164DE9AAFA0>
INFO:root:register <autowrap.ConversionProvider.StdSetConverter object at 0x00000164DE9BD040>
INFO:root:register <autowrap.ConversionProvider.StdMapConverter object at 0x00000164DE9BD0A0>
INFO:root:register <autowrap.ConversionProvider.StdPairConverter object at 0x00000164DE9BD100>
INFO:root:register <autowrap.ConversionProvider.VoidConverter object at 0x00000164DE9BD160>
INFO:root:register <autowrap.ConversionProvider.SharedPtrConverter object at 0x00000164DE9BD1C0>
INFO:root:register <autowrap.ConversionProvider.TypeToWrapConverter object at 0x00000164DE9BD250>
INFO:root:register <autowrap.ConversionProvider.TypeToWrapConverter object at 0x00000164DE9BD2B0>
INFO:root:register <autowrap.ConversionProvider.TypeToWrapConverter object at 0x00000164DE9BD310>
INFO:root:register <autowrap.ConversionProvider.TypeToWrapConverter object at 0x00000164DE9BD370>
INFO:root:Create foreign imports for module C:\Users\19707\Desktop\go-icp_cython-master\src\py_goicp.pyx
INFO:root:create wrapper for class GoICP
INFO:root:   create wrapper for non overloaded constructor __init__
INFO:root:   create wrapper for Register ('float Register()')
INFO:root:   create wrapper for BuildDT ('void BuildDT()')
INFO:root:   create wrapper for optimalRotation ('libcpp_vector[libcpp_vector[double]] optimalRotation()')
INFO:root:   create wrapper for optimalTranslation ('libcpp_vector[double] optimalTranslation()')
INFO:root:   create wrapper for loadModelAndData ('void loadModelAndData(int, libcpp_vector[POINT3D], int, libcpp_vector[POINT3D])')
INFO:root:   create wrapper for setInitNodeRot ('void setInitNodeRot(ROTNODE &)')
INFO:root:   create wrapper for setInitNodeTrans ('void setInitNodeTrans(TRANSNODE &)')
INFO:root:   create wrapper for setDTSizeAndFactor ('void setDTSizeAndFactor(int, double)')
INFO:root:create wrapper for class POINT3D
INFO:root:   create wrapper for non overloaded constructor _init_0
INFO:root:   create wrapper for non overloaded constructor _init_1
INFO:root:   create wrapper decl for overloaded method __init__
INFO:root:   create wrapper for pointToString ('void pointToString()')
INFO:root:create wrapper for class ROTNODE
INFO:root:   create wrapper for non overloaded constructor __init__
INFO:root:create wrapper for class TRANSNODE
INFO:root:   create wrapper for non overloaded constructor __init__
Autowrap has wrapped 4 classes, 13 methods and 0 enums
running build_ext
building 'py_goicp' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\19707\miniconda3\envs\connor\lib\site-packages\autowrap\data_files\autowrap -IC:\Users\19707\miniconda3\envs\connor\lib\site-packages\autowrap\data_files -IC:\Users\19707\miniconda3\envs\connor\include -IC:\Users\19707\miniconda3\envs\connor\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include" /EHsc /Tpsrc/py_goicp.cpp /Fobuild\temp.win-amd64-3.8\Release\src/py_goicp.obj -std=c++14
cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
py_goicp.cpp
C:\Users\19707\miniconda3\envs\connor\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by aalavandhaann** [comment]
Great and thanks for the error logs. I believe the pip install fails
because of the encoding error with Windows. But the manual compilation
looks fine. I guess the Python headers aren't setup the right way. Try to
install anaconda and try that maybe? I had some users complaining about
this in the past for Windows 10. However, I was about to compile (both pip
and manual) without issues on Windows 10. Or try fixing the Python headers

Check this link
1-
https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory
2- https://github.com/Jonathan-LeRoux/lws/issues/4

Most probably it looks like Windows SDK not in path. You are almost there
and in my opinion this is merely an issue with paths in your Windows
system.

Regards,
#0K

**Comment by connorhazen** [comment]
Alright thank you so much for the suggestions, I will give them a try tomorrow and let you know. Thanks again for the support, I appreciate you taking the time to help.

**Comment by aalavandhaann** [comment]
No worries and you are welcome the most. I will login to my Windows system
tomorrow. Let me know if you still have any issues and I will see what I
can do to help.

Regards,
#0K

**Comment by pareespathak** [comment]
> Alright thank you so much for the suggestions, I will give them a try tomorrow and let you know. Thanks again for the support, I appreciate you taking the time to help.

I am still getting the same error. Can you please suggest to me how to solve this?
